name: patient
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dart_mappable: ^4.4.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.6
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.4.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
