name: PR Workflow
on:
  pull_request:
  workflow_dispatch:

jobs: 
  Android-Build-Patient:
    name: Patient | Testing build for android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: "stable"
      - name: Change directory to patient
        run: cd patient
      - name: Running pub get to fetch dependencies
        run: flutter pub get
      - name: Building for android
        run: flutter build apk
        
  Android-Build-Therapist:
    name: Therapist | Testing build for android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: "stable"
      - name : Change directory to therapist
        run: cd therapist
      - name: Running pub get to fetch dependencies
        run: flutter pub get
      - name: Building for android
        run: flutter build apk
